[alias]
rel = "build --release"
inst = "install --path ."
clip = "clippy --release"
pub = "publish"
# Musl doesn't build because of openssl

[build]
target = "x86_64-unknown-linux-gnu"

[install]
target = "x86_64-unknown-linux-gnu"

[publish]
target = "x86_64-unknown-linux-gnu"

[clippy]
target = "x86_64-unknown-linux-gnu"
